### ISSUE TITLE
http://computing.caes.ucdavis.edu/faq/prepurchasing/i-keep-getting-errors

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/cru-computing#10]
The text needs to look exactly like this:
Some, One <someone@ucdavis.edu>  . It should have a mailto in it and the <> characters should be visible.

It is from this uservoice article:
https://ucdavis.uservoice.com/knowledgebase/articles/196628-i-keep-getting-errors-when-i

**Comment by cszhu** [comment]
Fixed 👍
