### ISSUE TITLE
http://computing.caes.ucdavis.edu/faq/prepurchasing/why-didnt-order-route

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/cru-computing#11]
There is a link to uservoice:
https://ucdavis.uservoice.com/knowledgebase/articles/111150-approver-was-bypassed-and-it-is-in-the-account-man

You will need to create a new article in PrePurchasing and call it Approver was bypassed and it is in the Account Manager stage

**Comment by cszhu** [comment]
I already had the article, but I updated the link.
