### ISSUE TITLE
http://computing.caes.ucdavis.edu/faq/evals/ace-staff-setup-instructions

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/cru-computing#13]
This is missing 2 links to articles:
Create the 2 articles in Evals and add links to the ace-staff-setup-instructions

https://ucdavis.uservoice.com/knowledgebase/articles/377483-ace-new-features-june-2014
Call it Ace Updated Features June 2014

https://ucdavis.uservoice.com/knowledgebase/articles/472015-ace-new-features-january-2015
Call it Ace Updated Features January 2015

**Comment by cszhu** [comment]
Fixed 👍
