### ISSUE TITLE
http://computing.caes.ucdavis.edu/faq/prepurchasing/welcome-to-prepurchasing

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/cru-computing#9]
1) Markup text is showing up "##The Landing Page"
2) Has a link to uservoice site: https://ucdavis.uservoice.com/knowledgebase/articles/126550-approval-routing. You will need to create this article in prepurchasing and call it "Approval Routing"
3) Remove the contact support stuff at the bottom. This is uservoice specific.

**Comment by cszhu** [comment]
Fixed :)
